CREATE TABLE doctors (
    id UUID PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    specialty VARCHAR(40) NOT NULL CHECK (specialty IN (
    'CARDIOLOGY', 'DERMATOLOGY', 'PEDIATRICS', 'ORTHOPEDICS', 'NEUROLOGY', 'GYNECOLOGY',
    'PSYCHIATRY', 'OPHTHALMOLOGY', 'ONCOLOGY', 'GENERAL_PRACTICE')),
    active BOOLEAN NOT NULL
);
